### ISSUE TITLE
Bug - Tag "Darling_In_The_Franxx" terminating early, downloading empty non image files

### ISSUE THREAD

**Issue by zpalmtree** [zpalmtree/r34-downloader#11]

**Comment by Acc12345** [comment]
Hi. I'm having this same problem with others tags. Can I have your discord? I would like to talk with you about. I could buy you "a coffe" or something. Thank you in advance, anyway!

**Comment by zpalmtree** [comment]
Can no longer reproduce this. Possibly fixed by f07d10a21817cbf89c654b455e73010fc9d20cb1
