### ISSUE TITLE
Open GL Context Error

### ISSUE THREAD

**Issue by cremia4** [zpalmtree/r34-downloader#13]
![rule34downloadererror](https://user-images.githubusercontent.com/46462653/52987613-306b5500-33d2-11e9-8320-0c29a9883dc6.png)

I get This Error After Installation

**Comment by zpalmtree** [comment]
Hiya,

A quick search indicates this is most likely a problem with your graphics drivers. Can you ensure they are up to date? I just tried the program on my machine, and it's working fine.

Thanks.
