### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Acc12345** [zpalmtree/r34-downloader#14]
.

**Comment by zpalmtree** [comment]
I think I remember seeing this before.. do you have an example of a tag which fails?

**Comment by Acc12345** [comment]
Sure. Some of the tags that didn't work: flannery, jasmine, nessa.

**Comment by Acc12345** [comment]
> I think I remember seeing this before.. do you have an example of a tag which fails?

The error occurs with any tag with many results. Do you think you could fix this? Also, do you have any patreon or something? Somewhere I can contribute to the project?
