### ISSUE TITLE
Bug - Images with file names containing Semicolans saves improperly on Windows

### ISSUE THREAD

**Issue by Faganj-y11** [zpalmtree/r34-downloader#15]
First noticed this with the tag _"Felix_Argyle"_ as file names would contain _"Re%3A_Life_in_a_Different_World_from_Zero"_. When the image is downloaded the name appears truncated from the semicolon onward. After some investigation I've found that Windows treats such a file with semicolons as Alternate Data Streams. The files are written to the disc but just aren't accessible by normal means.

**Comment by zpalmtree** [comment]
Thanks for the report. This looks like an easy fix, just need to run https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Windows.html#v:makeValid on the path before saving it.

I'll test it out, might take a little while to get a new build up though, as I don't think I have a development environment setup on windows anymore.

**Comment by zpalmtree** [comment]
Should be fixed by f07d10a21817cbf89c654b455e73010fc9d20cb1 , but have not yet tested on windows. Working on setting up windows environment to test and make a release now.

**Comment by zpalmtree** [comment]
Tested on windows, and I can download all the files successfully. I have uploaded a new release here - https://github.com/zpalmtree/r34-downloader/releases/tag/v0.1.1

Let me know if it doesn't fix your issue.
