### ISSUE TITLE
Doesn't collect any images

### ISSUE THREAD

**Issue by NexxDoor** [zpalmtree/r34-downloader#16]
Stuck on "0 images" and doesn't download anything.

**Comment by zpalmtree** [comment]
Which tag?

**Comment by NexxDoor** [comment]
> Which tag?

Almost every tag, also tried doing the popular ones too. (Mario, zelda, etc)

**Comment by zpalmtree** [comment]
OK. The website doesn't have an API, so we just download the HTML and parse it to find the images. It's possibly they changed the layout of their HTML, so the parsing no longer works. I'll take a look when possibly, not at a computer right now due to the holidays.

Thanks for the report!

**Comment by zpalmtree** [comment]
Sorry for the slow response, been busy with some other projects unfortunately. As I suspected, the site itself had slightly altered the returned HTML causing the parsing to fail. This has now been fixed.

Next steps are to make a new release, which I will do ASAP.

**Comment by zpalmtree** [comment]
New working installer has been uploaded - https://github.com/zpalmtree/r34-downloader/releases/tag/v0.1.2
Apologies for the delay.
