### ISSUE TITLE
Symbols cannot be recognised

### ISSUE THREAD

**Issue by Cimedaca618** [zpalmtree/r34-downloader#18]
Some symbols (for example, ".") cannot be recognised by a program.

**Comment by zpalmtree** [comment]
By this, do you mean that a tag containing `.` will not be searchable/downloadable? Do you have an example tag it fails on?

**Comment by Cimedaca618** [comment]
Of course! "D.Va"

**Comment by zpalmtree** [comment]
This is fixed now in v0.1.3: https://github.com/zpalmtree/r34-downloader/releases/tag/v0.1.3

Thanks for the report!
