### ISSUE TITLE
mismatch with some tags

### ISSUE THREAD

**Issue by BonMalYan** [zpalmtree/r34-downloader#21]
There are few search that the program cannot find any tag with the same characters, but then, when I check the web page, i can find it.
One of the tags is "Helltaker".

**Comment by zpalmtree** [comment]
I'm not really sure what's causing this. We use this page to find available tags: http://rule34.paheal.net/tags?starts_with=h&mincount=1

For some reason this tag just isn't present.

I think we could instead try and use the search endpoint. Inspecting the network requests, it looks like http://rule34.paheal.net/api/internal/autocomplete?s=helltaker returns the correct results.

**Comment by zpalmtree** [comment]
I've fixed this in b29aec9. Going to take a few days before I can make a release because I might include some other fixes as well.
