### ISSUE TITLE
Error while installing in linux

### ISSUE THREAD

**Issue by crossdefalt** [zpalmtree/r34-downloader#25]
Progress 63/73        

--  While building package hsqml-0.3.5.0 (scroll up to its section to see the error) using:
      /tmp/stack-d08c88b86b654570/hsqml-0.3.5.0/.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.24.2.0 configure --with-ghc=/home/s1yn/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/bin/ghc-8.0.2 --with-ghc-pkg=/home/s1yn/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/bin/ghc-pkg-8.0.2 --user --package-db=clear --package-db=global --package-db=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/pkgdb --libdir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/lib --bindir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/bin --datadir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/share --libexecdir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/libexec --sysconfdir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/etc --docdir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/doc/hsqml-0.3.5.0 --htmldir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/doc/hsqml-0.3.5.0 --haddockdir=/home/s1yn/.stack/snapshots/x86_64-linux-tinfo6/a76b5accb3e4698c1ccb6021f7feb0020fc9ffcbff06a1a37112202fded3e6e3/8.0.2/doc/hsqml-0.3.5.0 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=containers=containers-0.5.7.1 --dependency=filepath=filepath-1.4.1.1 --dependency=tagged=tagged-0.8.5-2FekbWvTugh4DIn4tSwH37 --dependency=template-haskell=template-haskell-2.11.1.0 --dependency=text=text-1.2.2.2-CHS1aCD6o4uK4fm30vavBX --dependency=transformers=transformers-0.5.2.0 -f-enableqmldebugging -fforceghcilib -fthreadedtestsuite -fuseexithook -f-usepkgconfig --exact-configuration
    Process exited with code: ExitFailure 1

**Comment by zpalmtree** [comment]
I don't think the error is included in this log, do you see it elsewhere in the log? `hsqml` can be a real pain to get installed

**Comment by crossdefalt** [comment]
This has to be some f~~ked up dependencies. You can close this issue if you want

**Comment by zpalmtree** [comment]
Yeah, sadly was not the greatest library to build the GUI on. Feel free to leave more messages if you need help debugging the issue, getting the right QT libraries to get hsqml building right can be confusing
